### ISSUE TITLE
Failed to connect to RabbitMQ: dial tcp [::1]:5672: connect: connection refused

### ISSUE THREAD

**Issue by syordanov94** [carlosm27/rabbitmq-demo#2]
Hello!

First of all, congrats on the implementation!

I tried running it but I'm getting the following error:

_Failed to connect to RabbitMQ: dial tcp [::1]:5672: connect: connection refused_

I think that this is caused because I don't have a RabbitMQ server running. Maybe you can add a docker-compose.yaml with the rabbitMQ server init. This can also be included in the Readme

**Comment by carlosm27** [comment]
Hey @syordanov94 thank you for rising this issue. I forget to add the link to [the article](https://www.rabbitmq.com/download.html) published in the README. But also, I will add the requirements to run this repo.

Have a nice day.
